DROP TABLE IF EXISTS commentupvote CASCADE;
DROP TABLE IF EXISTS projectapplicant CASCADE;
DROP TABLE IF EXISTS rewardlog CASCADE;
DROP TABLE IF EXISTS comment CASCADE;
DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS branch CASCADE;
