"""rbac_real

Revision ID: 51d1ee14896a
Revises: e8491a9be95f
Create Date: 2026-03-27 23:33:51.181561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '51d1ee14896a'
down_revision: Union[str, Sequence[str], None] = 'e8491a9be95f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('target_user', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    pass
    op.add_column('user', sa.Column('is_banned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user', sa.Column('is_suspended', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user', sa.Column('suspended_until', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('rejection_handled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rejection_handled')
    op.drop_column('user', 'suspended_until')
    op.drop_column('user', 'is_suspended')
    op.drop_column('user', 'is_banned')
    pass
    op.drop_table('auditlog')
    # ### end Alembic commands ###
