"""admin_welcome

Revision ID: 5ca4e7297734
Revises: 51d1ee14896a
Create Date: 2026-03-27 23:57:07.580549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca4e7297734'
down_revision: Union[str, Sequence[str], None] = '51d1ee14896a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.add_column('user', sa.Column('has_seen_admin_welcome', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_seen_admin_welcome')
    pass
    # ### end Alembic commands ###
