"""add_institution_table

Revision ID: e8491a9be95f
Revises: 9c9cb8f7105a
Create Date: 2026-03-25 19:16:36.545450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8491a9be95f'
down_revision: Union[str, Sequence[str], None] = '9c9cb8f7105a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'branch', 'institution', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branch', type_='foreignkey')
    op.drop_column('branch', 'institution_id')
    # ### end Alembic commands ###
